apiVersion: apps/v1
kind: Deployment
metadata:
  name: processmc-deployment 
  labels:
    app: processmc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processmc
  template:
    metadata:
      labels:
        app: processmc
    spec:
      containers:
      - name: processmc
        image: pensioncr.azurecr.io/processmcimage:latest
        resources:
        env:
           - name: ConnectionString
             value: Server = "tcp:authpension.database.windows.net,1433;Initial Catalog=MSTWOPensionDb;Persist Security Info=False;User ID=pension;Password=Subhadip@1202;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: webapisvcsecret  
---


apiVersion: v1
kind: Service
metadata:
  name: processmcsvc
spec:
  type: LoadBalancer
  selector:
    app: processmc
  ports:
  - port: 80
